In [1]:
import numpy as np
from Ejercicio1 import springs

In [2]:
mysprings = springs()

In [3]:
K = mysprings.K

In [4]:
r = mysprings.r

In [20]:
r

array([1, 2])

In [5]:
s = mysprings.s

In [21]:
s

array([0, 3])

In [6]:
F = mysprings.F

In [24]:
K[1:3,1:3]

array([[ 400., -200.],
       [-200.,  400.]])

In [25]:
K[[1,2],[1,2]]

array([400., 400.])

In [22]:
K[np.ix_(r,r)]

array([[ 400., -200.],
       [-200.,  400.]])

In [28]:
K[np.ix_(r,s)]

array([[-200.,    0.],
       [   0., -200.]])

In [7]:
U = mysprings.U

In [34]:
U[s]

array([[0.   ],
       [0.002]])

In [39]:
Us = np.array([[0], [0.002]])

In [40]:
Us

array([[0.   ],
       [0.002]])

In [35]:
s

array([0, 3])

In [41]:
Ur = np.linalg.solve(K[np.ix_(r,r)], F[r] -K[np.ix_(r,s)].dot(U[s]))

In [42]:
Ur

array([[0.00066667],
       [0.00133333]])

In [43]:
U = np.zeros([4,1])

In [44]:
U

array([[0.],
       [0.],
       [0.],
       [0.]])

In [45]:
U[s] = Us

In [46]:
U[r] = Ur

In [47]:
U

array([[0.        ],
       [0.00066667],
       [0.00133333],
       [0.002     ]])

In [15]:
K[np.ix_(r,s)]

array([[-200.,    0.],
       [   0., -200.]])

In [16]:
K

array([[ 200., -200.,    0.,    0.],
       [-200.,  400., -200.,    0.],
       [   0., -200.,  400., -200.],
       [   0.,    0., -200.,  200.]])

In [17]:
F

array([[-0.13333333],
       [ 0.        ],
       [ 0.        ],
       [ 0.13333333]])

In [ ]:
U

In [48]:
F = U = np.zeros([4,1])

In [49]:
F[0] = 1

In [50]:
U

array([[1.],
       [0.],
       [0.],
       [0.]])