In [1]:
import numpy as np
from Ejercicio1 import springs

In [2]:
mysprings = springs()

In [3]:
K = mysprings.K

In [4]:
r = mysprings.r

In [5]:
r

array([1, 2])

In [6]:
s = mysprings.s

In [7]:
s

array([0, 3])

In [8]:
F = mysprings.F

In [9]:
K[1:3,1:3]

array([[ 400., -200.],
       [-200.,  400.]])

In [10]:
K[[1,2],[1,2]]

array([400., 400.])

In [11]:
K[np.ix_(r,r)]

array([[ 400., -200.],
       [-200.,  400.]])

In [12]:
K[np.ix_(r,s)]

array([[-200.,    0.],
       [   0., -200.]])

In [13]:
U = mysprings.U

In [14]:
U[s]

array([[0.   ],
       [0.002]])

In [15]:
Us = np.array([[0], [0.002]])

In [16]:
Us

array([[0.   ],
       [0.002]])

In [17]:
s

array([0, 3])

In [18]:
Ur = np.linalg.solve(K[np.ix_(r,r)], F[r] -K[np.ix_(r,s)].dot(U[s]))

In [19]:
Ur

array([[0.00066667],
       [0.00133333]])

In [20]:
U = np.zeros([4,1])

In [21]:
U

array([[0.],
       [0.],
       [0.],
       [0.]])

In [22]:
U[s] = Us

In [23]:
U[r] = Ur

In [24]:
U

array([[0.        ],
       [0.00066667],
       [0.00133333],
       [0.002     ]])

In [25]:
K[np.ix_(r,s)]

array([[-200.,    0.],
       [   0., -200.]])

In [26]:
K

array([[ 200., -200.,    0.,    0.],
       [-200.,  400., -200.,    0.],
       [   0., -200.,  400., -200.],
       [   0.,    0., -200.,  200.]])

In [27]:
F

array([[-0.13333333],
       [ 0.        ],
       [ 0.        ],
       [ 0.13333333]])

In [35]:
K.dot(U)

array([[-0.13333333],
       [ 0.00000000],
       [ 0.00000000],
       [ 0.13333333]])

In [34]:
np.set_printoptions(floatmode='fixed', suppress=True)