In [10]:
from importlib.machinery import SourceFileLoader
import numpy as np

In [2]:
springs = SourceFileLoader(
    'springs',
    'Ejercicio1.py'
).load_module().springs()

In [5]:
K = springs.K

In [8]:
r = springs.r

In [9]:
s = springs.s

In [18]:
F = springs.F

In [19]:
U = springs.U

In [28]:
np.linalg.solve(K[np.ix_(r,r)], K[np.ix_(r,s)].dot(U[s]))

array([[-0.00066667],
       [-0.00133333]])

In [37]:
K[np.ix_(r,s)]

array([[-200.,    0.],
       [   0., -200.]])

In [35]:
K

array([[ 200., -200.,    0.,    0.],
       [-200.,  400., -200.,    0.],
       [   0., -200.,  400., -200.],
       [   0.,    0., -200.,  200.]])

In [31]:
i = 0
while True:
    i+=1
#    if i > 10:
#        break
    pass

print(i)

KeyboardInterrupt: 